openapi: 3.0.1
info:
  title: Emlakcepte Payment API
  description: Payment API Information
  version: "1.0"
servers:
- url: http://localhost:9095
  description: Generated server url
paths:
  /payment/{cardNo}/{extensionAmount}:
    post:
      tags:
      - payment-controller
      operationId: processPayment
      parameters:
      - name: cardNo
        in: path
        required: true
        schema:
          type: string
      - name: extensionAmount
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Payment'
components:
  schemas:
    Payment:
      type: object
      properties:
        userId:
          type: integer
          format: int32
        cardNo:
          type: string
