server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
        - id: STOCK-SERVICE
          uri: lb://stock-service
          predicates:
            - Path=/api/v1/stocks/**
        - id: PAYMENT-SERVICE
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
        - id: REVENUE-SERVICE
          uri: lb://revenue-service
          predicates:
            - Path=/api/v1/revenues/**

eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"